# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imp1matsigma <- function(D, muest, sigest) {
    .Call('_EMgaussian_imp1matsigma', PACKAGE = 'EMgaussian', D, muest, sigest)
}

imp2matsigma <- function(d, sigest, t2) {
    invisible(.Call('_EMgaussian_imp2matsigma', PACKAGE = 'EMgaussian', d, sigest, t2))
}

nllcov <- function(d, muest, sigest, np) {
    .Call('_EMgaussian_nllcov', PACKAGE = 'EMgaussian', d, muest, sigest, np)
}

imp1mat <- function(D, muest, kest) {
    .Call('_EMgaussian_imp1mat', PACKAGE = 'EMgaussian', D, muest, kest)
}

imp2mat <- function(d, kest, t2) {
    invisible(.Call('_EMgaussian_imp2mat', PACKAGE = 'EMgaussian', d, kest, t2))
}

nllprec <- function(d, muest, kest, np) {
    .Call('_EMgaussian_nllprec', PACKAGE = 'EMgaussian', d, muest, kest, np)
}

