# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imp1matcov <- function(D, muest, sigest) {
    .Call('_EMgaussian_imp1matcov', PACKAGE = 'EMgaussian', D, muest, sigest)
}

imp2matcov <- function(D, sigest, t2) {
    invisible(.Call('_EMgaussian_imp2matcov', PACKAGE = 'EMgaussian', D, sigest, t2))
}

EMcyclecov <- function(D, muest, sigest) {
    .Call('_EMgaussian_EMcyclecov', PACKAGE = 'EMgaussian', D, muest, sigest)
}

#' Negative log-likelihood, covariance matrix parameterization
#' 
#' @param dat (matrix) data.
#' @param mu (vector) means.
#' @param sig (matrix) covariance matrix.
#' @details Computes the negative log-likelihood under missing data for the given value of means and covariances.
#' @return Numeric value of the negative log-likelihood.
#' @export
nllcov <- function(dat, mu, sig) {
    .Call('_EMgaussian_nllcov', PACKAGE = 'EMgaussian', dat, mu, sig)
}

imp1matprec <- function(D, muest, kest) {
    .Call('_EMgaussian_imp1matprec', PACKAGE = 'EMgaussian', D, muest, kest)
}

imp2matprec <- function(D, kest, t2) {
    invisible(.Call('_EMgaussian_imp2matprec', PACKAGE = 'EMgaussian', D, kest, t2))
}

EMcycleprec <- function(D, muest, kest) {
    .Call('_EMgaussian_EMcycleprec', PACKAGE = 'EMgaussian', D, muest, kest)
}

#' Negative log-likelihood, precision matrix parameterization
#' @param dat (matrix) data.
#' @param mu (vector) means.
#' @param K (matrix) precision matrix.
#' @details Computes the negative log-likelihood under missing data for the given value of means and precision matrix.
#' @return Numeric value of the negative log-likelihood.
#' @export        
nllprec <- function(dat, mu, K) {
    .Call('_EMgaussian_nllprec', PACKAGE = 'EMgaussian', dat, mu, K)
}

