# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imp1matcov <- function(D, muest, sigest) {
    .Call('_EMgaussian_imp1matcov', PACKAGE = 'EMgaussian', D, muest, sigest)
}

imp2matcov <- function(D, sigest, t2) {
    invisible(.Call('_EMgaussian_imp2matcov', PACKAGE = 'EMgaussian', D, sigest, t2))
}

EMcyclecov <- function(D, muest, sigest) {
    .Call('_EMgaussian_EMcyclecov', PACKAGE = 'EMgaussian', D, muest, sigest)
}

nllcov <- function(d, muest, sigest, np) {
    .Call('_EMgaussian_nllcov', PACKAGE = 'EMgaussian', d, muest, sigest, np)
}

imp1matprec <- function(D, muest, kest) {
    .Call('_EMgaussian_imp1matprec', PACKAGE = 'EMgaussian', D, muest, kest)
}

imp2matprec <- function(D, kest, t2) {
    invisible(.Call('_EMgaussian_imp2matprec', PACKAGE = 'EMgaussian', D, kest, t2))
}

EMcycleprec <- function(D, muest, kest) {
    .Call('_EMgaussian_EMcycleprec', PACKAGE = 'EMgaussian', D, muest, kest)
}

nllprec <- function(d, muest, kest, np) {
    .Call('_EMgaussian_nllprec', PACKAGE = 'EMgaussian', d, muest, kest, np)
}

